### ISSUE TITLE
'shotGroups' installation error (R v3.2.5)

### ISSUE THREAD

**Issue by JoGall** [dwoll/shotGroups#1]
'shotGroups' is currently failing to install for me due to a compilation failure of a dependency, 'CompQuadForm'. This appears due to some non-member issues in its source file 'imhof.cpp' (error message included below). I'm using the latest version of R (v3.2.5).

I've copied the key functions used in getMinCircle() from your R examples repository to bundle with my own package (citing you of course!) in the meantime until this is rectified -- I hope this is ok?

Thanks for the min circle implementation by the way -- very handy!

```
* installing *source* package ‘CompQuadForm’ ...
** package ‘CompQuadForm’ successfully unpacked and MD5 sums checked
** libs
g++ -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c imhof.cpp -o imhof.o
imhof.cpp: In function ‘double theta(double*, double*, int*, double*, double*, double*)’:
imhof.cpp:18:59: error: ‘atan’ is not a member of ‘std’
imhof.cpp:18:59: note: suggested alternative:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:59:1: note:   ‘atan’
imhof.cpp: In function ‘double rho(double*, double*, int*, double*, double*)’:
imhof.cpp:29:116: error: ‘exp’ is not a member of ‘std’
imhof.cpp:29:116: note: suggested alternative:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:101:1: note:   ‘exp’
imhof.cpp: In function ‘double imhoffunc(double*, double*, int*, double*, double*, double*)’:
imhof.cpp:40:12: error: ‘sin’ is not a member of ‘std’
imhof.cpp:40:12: note: suggested alternative:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:66:1: note:   ‘sin’
make: *** [imhof.o] Error 1
ERROR: compilation failed for package ‘CompQuadForm’
```

**Comment by dwoll** [comment]
Sure, you're welcome to copy any code that seems useful to you given your package is GPL'ed. Just note that in case you intend to publish to CRAN, its [policies](https://cran.r-project.org/web/packages/policies.html#Source-packages) recommend adding authors from copied code with the role "contributor" (field "ctb") to `Authors@R`. See the [`knitr` DESCRIPTION](https://github.com/yihui/knitr/blob/master/DESCRIPTION) for an example.

Does this issue occur also with the latest stable version, i.e., R 3.3.1?

**Comment by JoGall** [comment]
Ok that's great -- thanks for the heads up.

I'm using an older Ubuntu release (12.04) and R 3.2.5. appears to be the most recent version available so can't test this on the latest version unfortunately!
