### ISSUE TITLE
Some targets not listed in help

### ISSUE THREAD

**Issue by memilanuk** [dwoll/shotGroups#2]
When viewing the help for `targets`, the listing of target faces shows the MR-1, but not MR-1FC.  Similarly, the NRA LR target is not listed in the same help, but the LRFC is.

The other NRA HP targets are shown as both their 'full size' (MR-63, MR-65, etc.) and F-class versions (MR-63FC, MR-65FC).

The actual target information does appear to be present for the NRA MR-1FC when listing `names("targets")`, just not in the help file.  The NRA LR target appears to be missing from that listing.

**Comment by dwoll** [comment]
Thanks for the report! This should be fixed in commit ef6f36febfa6269da0b28ebaa82917ee3b50b9fd.
