### ISSUE TITLE
Add group size values to target plot

### ISSUE THREAD

**Issue by memilanuk** [dwoll/shotGroups#3]
Is there a way (or plans for) to add the group size values directly to the plot when graphing shot locations on a target image?

As an example:
`> dg3 <- drawGroup(df3, xyTopLeft = FALSE, center = FALSE, bb = TRUE, maxSpread = TRUE, scaled = TRUE, caliber = 7.62, target = "NRA_MR1FC")`

yields [this plot](https://imgur.com/a/wJr05e5).

`> dg3$bb
...
$width
[1] 2.199678

$height
[1] 1.194111
...
$diag
[1] 2.502895
`

Is there a way to plot the width & height of the bounding box along the bottom and left line of the box, and the diag value along the maxSpread line?

**Comment by dwoll** [comment]
That should be possible. Might take a couple of days though.

**Comment by dwoll** [comment]
Work started in commit 67221bbb24ed584eee3823d03d5c0d24a162ec3f ...

**Comment by dwoll** [comment]
Now fully implemented in commit 6206cbbebc6d415c36026bf52829b93c6511e85a
Text positioning could be better though.
