### ISSUE TITLE
Integrating non-gaussian distributions over ellipse

### ISSUE THREAD

**Issue by adkinsty** [dwoll/shotGroups#5]
This is a question, not really an issue. Is there a straightforward way to adapt the code of `pmvnEll` so that it works with distributions other than the gaussian (e.g., t-distribution, gamma, exgaussian, etc.)? Or does the functionality depend critically on the assumption that the distribution is gaussian? 

Thanks!

**Comment by dwoll** [comment]
Thanks for your interest in the shotGroups package! As the current code ultimately is a wrapper for `CompQuadForm::farebrother()`, it is indeed restricted to a bivariate Gaussian distribution. To adapt it, you could replace line https://github.com/dwoll/shotGroups/blob/f319e3e63685a4387855dbe07bc73313963a74bf/R/mvnEll.R#L49 with a suitable call to `polyCub::polyCub()` which does numerical integration of arbitrary functions over polygonal domains. 

Roughly, the steps would be to define the elliptical integration domain by a set of (x,y) points on its boundary, convert them to a `gpc.poly` poly object, create your distribution function such that it accepts a matrix of points, and call `polyCub::polyCub()` using both.

Is this something you can work with?

**Comment by adkinsty** [comment]
You're welcome for the interest. I am modeling how humans reach at targets, and your `pmvnEll` function has made it very easy to estimate the expected outcomes of different strategies (aim-points). So, thank you for that. 

After some data exploration, I realized that a bivariate gaussian is indeed the best model of my participants' reaching endpoints. But I appreciate the advice, and I will follow up on it in the future if I find that I need to integrate some other types of functions.
